---
title: "Income"
output: github_document
---

```{r load_packages}
library(tidyverse)
library(knitr)
opts_knit$set(root.dir = normalizePath("../"))
```

```{r load_data include = FALSE}
if(!dir.exists("temp")) dir.create("temp")
purl("../data-raw/wrangle/cps.Rmd", output = "temp/cps.R") %>% source()
purl("../data-raw/wrangle/nc_cloud.Rmd", output = "temp/nc.R") %>% source()
purl("../data-raw/wrangle/tidy_cces.Rmd", output = "temp/cces.R") %>% source()
```

```{r cps}
ggplot(cps, aes(FAMINC)) +
  stat_count() +
  facet_wrap(~YEAR) +
  theme_bw() +
  labs(title = "CPS reported family income",
       x = "Family income",
       y = "Count")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
```

```{r cces}
ggplot(cces_2012, aes(faminc)) +
  stat_count() +
  #facet_wrap(~YEAR) +
  theme_bw() +
  labs(title = "CCES reported family income (2012)",
       x = "Family income",
       y = "Count")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

ggplot(cces_2014, aes(faminc)) +
  stat_count() +
  #facet_wrap(~YEAR) +
  theme_bw() +
  labs(title = "CCES reported family income (2014)",
       x = "Family income",
       y = "Count")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
```


