---
title: "race_voting_pop"
author: "Edwin Alvarado"
date: "April 13, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(knitr)
library(forcats)
```

```{r, load data}
if(!dir.exists("~/nc-elections-project/viz/temp")) dir.create("~/nc-elections-project/viz/temp")
purl("wrangle/cps.Rmd", output = "viz/temp/cps.R") %>% source()
purl("wrangle/nc_wrangle.Rmd", output = "viz/temp/nc.R") %>% source()
purl("tidy_cces/tidy_cces.Rmd", output = "viz/temp/cces.R") %>% source()
```

```{r, nc server}
my_db <- src_postgres("nc_elections",
                      host = "ncelections.c7d0c8vzwwoc.us-west-2.rds.amazonaws.com", 
                      port = 5432,
                      user = "nc_elections",
                      password = "nc_elections")
nc_vhis <- tbl(my_db, "nc_vhis")
nc_voter <- tbl(my_db, "nc_voter")
```

```{r, tidy cps for viz}
set.seed(42)
cps$HISPAN <- as.factor(cps$HISPAN)
cps$WTFINL <- as.numeric(cps$WTFINL)
cps$HISPAN <- fct_other(cps$HISPAN, keep = "Not Hispanic", other_level = "Hispanic")

#see cases that are hispanic
cps%>%
  group_by(RACE, HISPAN) %>%
  summarize(count = n())

#change race to hispanic
cps$VOTEREG <- as.factor(cps$VOTEREG)
cps <- cps %>%
  mutate(RACE = if_else(HISPAN == "Hispanic", true = "Hispanic", 
                        false = RACE, missing = RACE)) %>%
  filter(VOTEREG %in% c("Voted"),
         AGE >= 18)
#NoOtherCategoryWhen 
cps$RACE <- fct_recode(cps$RACE, `Native American` =  "American Indian/Aleut/Eskimo",
                       Asian = "Asian only",
                       Black = "Black-American Indian",
                       Mixed = "Black-Asian",
                       Black = "Black/Negro",
                       `Native American` = "White-American Indian",
                       Mixed = "White-Asian",
                       Mixed = "White-Black",
                       Mixed = "White-Black-American Indian")

cps_2012 <- filter(cps, YEAR == 2012)
cps_2014 <- filter(cps, YEAR == 2014)

cps_2012_viz <- sample_n(cps, size = nrow(cps_2012), weight = WTFINL, replace = TRUE)
cps_2014_viz <- sample_n(cps, size = nrow(cps_2014), weight = WTFINL, replace = TRUE)

cps_2012_viz <- cps_2012_viz %>%
  mutate(source = "cps2012", race = RACE) %>%
  select(race, source)

cps_2014_viz <- cps_2014_viz %>%
  mutate(source = "cps2014", race = RACE) %>%
  select(race, source)
rm(list = c("cps", "cps_2012", "cps_2014"))
```

```{r, nc}
nc_race <- nc %>%
  filter(!is.na(race_code), 
         race_code != "U",
         !is.na(ethnic_code),
                age < 122) %>%
  select(race_code, ethnic_code, age, registr_dt) %>%
  collect(n = Inf)

nc_race <- nc_race %>%
  mutate(race_code = if_else(ethnic_code == "HL", true = "Hispanic", 
                        false = race_code, missing = race_code))
#16 cases where race is a space
nc_race <- filter(nc_race, race_code != " ")
nc_race$race_code <- fct_recode(nc_race$race_code,
                                `Native American` = "I",
                                Asian = "A",
                                Black = "B",
                                Mixed = "M",
                                Other = "O",
                                White = "W")
nc_race_2012 <- nc_race %>%
  filter(registr_dt <= as.Date("2012-10-16")) %>%
  mutate(race = race_code, source = "nc2012") %>%
  select(race, source)

nc_race_2014 <- nc_race %>%
  filter(registr_dt <= as.Date("2014-10-13")) %>%
  mutate(race = race_code, source = "nc2014") %>%
  select(race, source)
#optional remove nc_race file
#rm(nc_race)
```

```{r, 2012 viz}
full_data <- rbind(cps_2012_viz, cps_2014_viz, nc_race_2012, nc_race_2014)
#optional removal of all data except full data
#rm(c("cps_2012_viz", "cps_2014_viz", "nc_race_2012", "nc_race_2014"))

to_plot_2012 <- full_data %>%
  group_by(source) %>%
  summarise(n = n()) %>% 
  right_join(full_data, by = "source") %>%
  filter(source %in% c("cces2012", "cps2012", "nc2012")) %>%
  group_by(source, race) %>% 
  summarise(prop = n()/median(n))

ggplot(to_plot_2012, aes(x = source, y = prop, fill = race)) +
  geom_col(position = "dodge")
#zoom
ggplot(to_plot_2012, aes(source, prop, fill = race)) +
  geom_col(position = "dodge") +
 coord_cartesian(ylim = c(0,.25)) +
  geom_text(aes(label = round(prop, digits = 3)), 
            vjust = -.05,
            position = position_dodge(0.9),
            size = 2.5)
#extra
ggplot(to_plot_2012, aes(x = race, y = prop, fill = source)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = round(prop, digits = 3)), 
            vjust = -.05,
            position = position_dodge(0.9),
            size = 2.5)
```

```{r, 2014}
to_plot_2014 <- full_data %>%
  group_by(source) %>%
  summarise(n = n()) %>% 
  right_join(full_data, by = "source") %>%
  filter(source %in% c("cces2014", "cps2014", "nc2014")) %>%
  group_by(source, race) %>% 
  summarise(prop = n()/median(n))

ggplot(to_plot_2014, aes(x = source, y = prop, fill = race)) +
  geom_col(position = "dodge")
#zoom
ggplot(to_plot_2014, aes(source, prop, fill = race)) +
  geom_col(position = "dodge") +
 coord_cartesian(ylim = c(0,.25)) +
  geom_text(aes(label = round(prop, digits = 3)), 
            vjust = -.05,
            position = position_dodge(0.9),
            size = 2.5)
#extra
ggplot(to_plot_2014, aes(x = race, y = prop, fill = source)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = round(prop, digits = 3)), 
            vjust = -.05,
            position = position_dodge(0.9),
            size = 2.5)
```

```{r, 2016}
to_plot_2016 <- full_data %>%
  group_by(source) %>%
  summarise(n = n()) %>% 
  right_join(full_data, by = "source") %>%
  filter(source %in% c("cces2016", "nc2016")) %>%
  group_by(source, race) %>% 
  summarise(prop = n()/median(n))

ggplot(to_plot_2016, aes(x = source, y = prop, fill = race)) +
  geom_col(position = "dodge")
#zoom
ggplot(to_plot_2016, aes(source, prop, fill = race)) +
  geom_col(position = "dodge") +
 coord_cartesian(ylim = c(0,.25)) +
  geom_text(aes(label = round(prop, digits = 3)), 
            vjust = -.05,
            position = position_dodge(0.9),
            size = 3)
#extra
ggplot(to_plot_2016, aes(x = race, y = prop, fill = source)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = round(prop, digits = 3)), 
            vjust = -.05,
            position = position_dodge(0.9),
            size = 3)
```