---
title: "race_viz"
author: "Edwin Alvarado"
date: "April 13, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(knitr)
library(forcats)
```

```{r, load data}
if(!dir.exists("temp")) dir.create("temp")
purl("../data-raw/wrangle/cps.Rmd", output = "temp/cps.R") %>% source()
purl("../data-raw/wrangle/nc_cloud.Rmd", output = "temp/nc.R") %>% source()
purl("../data-raw/wrangle/tidy_cces.Rmd", output = "temp/cces.R") %>% source()
```

```{r, nc server}
my_db <- src_postgres("nc_elections",
                      host = "ncelections.c7d0c8vzwwoc.us-west-2.rds.amazonaws.com", 
                      port = 5432,
                      user = "nc_elections",
                      password = "nc_elections")
nc_vhis <- tbl(my_db, "nc_vhis")
nc_voter <- tbl(my_db, "nc_voter")
```

```{r, tidy cps for viz}
set.seed(42)
cps$HISPAN <- as.factor(cps$HISPAN)
cps$WTFINL <- as.numeric(cps$WTFINL)
cps$HISPAN <- fct_other(cps$HISPAN, keep = "Not Hispanic", other_level = "Hispanic")

#see cases that are hispanic
cps%>%
  group_by(RACE, HISPAN) %>%
  summarize(count = n())

#change race to hispanic
cps$VOTEREG <- as.factor(cps$VOTEREG)
cps <- cps %>%
  mutate(RACE = if_else(HISPAN == "Hispanic", true = "Hispanic", 
                        false = RACE, missing = RACE)) %>%
  filter(VOTEREG %in% c("Registered, did not vote", "Voted"),
         AGE >= 18)

cps$RACE <- fct_recode(cps$RACE, `Native American` =  "American Indian/Aleut/Eskimo",
                       Asian = "Asian only",
                       Black = "Black-American Indian",
                       Mixed = "Black-Asian",
                       Black = "Black/Negro",
                       Other = "Hawaiian/Pacific Islander only",
                       `Native American` = "White-American Indian",
                       Mixed = "White-Asian",
                       Mixed = "White-Black",
                       Mixed = "White-Black-American Indian")

cps$VOTEREG <- fct_other(cps$VOTEREG, keep = "Voted", other_level = "Registered Only")

cps <- rename(cps, voted = VOTEREG)

cps_2012 <- filter(cps, YEAR == 2012)
cps_2014 <- filter(cps, YEAR == 2014)

cps_2012_viz <- sample_n(cps, size = nrow(cps_2012), weight = WTFINL, replace = TRUE)
cps_2014_viz <- sample_n(cps, size = nrow(cps_2014), weight = WTFINL, replace = TRUE)

cps_2012_viz <- cps_2012_viz %>%
  mutate(source = "cps2012", race = RACE) %>%
  select(race, source, voted)

cps_2014_viz <- cps_2014_viz %>%
  mutate(source = "cps2014", race = RACE) %>%
  select(race, source, voted)
rm(list = c("cps", "cps_2012", "cps_2014"))
```

```{r, tidy cces for viz}
#this changes people who answered yes to hispanic, to hispanic in race column
cces_2012$race <- as.character(cces_2012$race)
cces_2012 <- cces_2012 %>%
  mutate(race = if_else(hispanic == "Yes", true = "Hispanic", 
                        false = race, missing = race))

cces_2012_viz <- sample_n(cces_2012, size = nrow(cces_2012), 
                          weight = weight_vv, replace = TRUE)

cces_2012_viz <- cces_2012_viz %>%
  mutate(source = "cces2012") %>%
  select(race, source, voted)

#2014
cces_2014$race <- as.character(cces_2014$race)
cces_2014 <- cces_2014 %>%
  mutate(race = if_else(hispanic == "Yes", true = "Hispanic", 
                        false = race, missing = race))
  
cces_2014$race <- fct_recode(cces_2014$race, Other = "Middle Eastern")

cces_2014_viz <- sample_n(cces_2014, size = nrow(cces_2014), 
                          weight = weight, replace = TRUE)

cces_2014_viz <- cces_2014_viz %>%
  mutate(source = "cces2014") %>%
  select(race, source, voted)

#2016
cces_2016$race <- as.character(cces_2016$race)
cces_2016 <- cces_2016 %>%
  mutate(race = if_else(hispanic == "Yes", true = "Hispanic", false = race, missing = race))
  
cces_2016$race <- fct_recode(cces_2016$race, Other = "Middle Eastern")

cces_2016_viz <- sample_n(cces_2016, size = nrow(cces_2016), 
                          weight = commonweight, replace = TRUE)

cces_2016_viz <- cces_2016_viz %>%
  mutate(source = "cces2016") %>%
  select(race, source, voted)
rm(list = c("cces_2012", "cces_2014", "cces_2016"))
```

```{r, nc}
nc_race <- nc %>% ungroup() %>% 
  filter(!is.na(race_code), 
         race_code != "U",
         !is.na(ethnic_code),
                age < 122) %>%
  select(race_code, ethnic_code, age, registr_dt, new_id, election_desc) %>%
  collect(n = Inf)

nc_race <- nc_race %>%
  mutate(race_code = if_else(ethnic_code == "HL", true = "Hispanic", 
                        false = as.character(race_code), missing = as.character(race_code))) %>%
  mutate(voted = ifelse(election_desc == "11/06/2012 GENERAL", "Voted2012",
                         election_desc)) %>%
  mutate(voted = ifelse(election_desc == "11/04/2014 GENERAL", "Voted2014",
                         voted)) %>%
  mutate(voted = ifelse(election_desc == "11/08/2016 GENERAL", "Voted2016",
                         voted))

#16 cases where race is a space
nc_race <- filter(nc_race, race_code != " ")
nc_race$race_code <- fct_recode(nc_race$race_code,
                                `Native American` = "I",
                                Asian = "A",
                                Black = "B",
                                Mixed = "M",
                                Other = "O",
                                White = "W")

#make standardized dataframe for registerd voters in diffeent years
nc_race_2012 <- nc_race %>%
  filter(mdy(registr_dt) <= as.Date("2012-10-16")) %>%
  mutate(race = race_code, source = "nc2012") %>%
  select(race, source, voted)

nc_race_2014 <- nc_race %>%
  filter(mdy(registr_dt) <= as.Date("2014-10-13")) %>%
  mutate(race = race_code, source = "nc2014") %>%
  select(race, source, voted)

nc_race_2016 <- nc_race %>%
  filter(mdy(registr_dt) <= as.Date("2016-10-18")) %>%
  mutate(race = race_code, source = "nc2016") %>%
  select(race, source, voted)

#make stadardized dataframe for voters in specific elections
nc_race_2012_vot <- nc_race %>%
  filter(voted == "Voted2012") %>%
  mutate(race = race_code, source = "nc2012vot") %>%
  select(race, source, voted)

nc_race_2014_vot <- nc_race %>%
  filter(voted == "Voted2014") %>%
  mutate(race = race_code, source = "nc2014vot") %>%
  select(race, source, voted)

nc_race_2016_vot <- nc_race %>%
  filter(voted == "Voted2016") %>%
  mutate(race = race_code, source = "nc2016vot") %>%
  select(race, source, voted)
#optional remove nc_race file
#rm(nc_race)
```

```{r, 2012 registered viz}
full_data <- rbind(cces_2012_viz, cces_2014_viz, cces_2016_viz, cps_2012_viz, 
                   cps_2014_viz, nc_race_2012, nc_race_2014, nc_race_2016,
                   nc_race_2012_vot, nc_race_2014_vot, nc_race_2016_vot)
#optional removal of all data except full data
#rm(c("cces_2012_viz", "cces_2014_viz", "cces_2016_viz", "cps_2012_viz", "cps_2014_viz", "nc_race_2012", "nc_race_2014", "nc_race_2016", nc_race_2012_vot, nc_race_2014_vot, nc_race_2016_vot))

to_plot_2012 <- full_data %>% ungroup() %>%
  filter(source %in% c("cces2012", "cps2012", "nc2012")) %>%
  group_by(source) %>%
  summarise(n = n()) %>% 
  right_join(full_data, by = "source") %>%
  group_by(source, race) %>% 
  summarise(prop = n()/median(n)) %>%
  filter(source %in% c("cces2012", "cps2012", "nc2012"))

ggplot(to_plot_2012, aes(x = source, y = prop, fill = race)) +
  geom_col(position = "dodge")
#zoom
ggplot(to_plot_2012, aes(source, prop, fill = race)) +
  geom_col(position = "dodge") +
 coord_cartesian(ylim = c(0,.25)) +
  geom_text(aes(label = round(prop, digits = 3)), 
            vjust = -.05,
            position = position_dodge(0.9),
            size = 2.5)
#extra
ggplot(to_plot_2012, aes(x = race, y = prop, fill = source)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = round(prop, digits = 3)), 
            vjust = -.05,
            position = position_dodge(0.9),
            size = 2.5)
```

```{r, 2014 registered}
to_plot_2014 <- full_data %>%
  filter(source %in% c("cces2014", "cps2014", "nc2014")) %>%
  group_by(source) %>%
  summarise(n = n()) %>% 
  right_join(full_data, by = "source") %>%
  group_by(source, race) %>% 
  summarise(prop = n()/median(n)) %>%
  filter(source %in% c("cces2014", "cps2014", "nc2014"))

ggplot(to_plot_2014, aes(x = source, y = prop, fill = race)) +
  geom_col(position = "dodge")
#zoom
ggplot(to_plot_2014, aes(source, prop, fill = race)) +
  geom_col(position = "dodge") +
 coord_cartesian(ylim = c(0,.25)) +
  geom_text(aes(label = round(prop, digits = 3)), 
            vjust = -.05,
            position = position_dodge(0.9),
            size = 2.5)
#extra
ggplot(to_plot_2014, aes(x = race, y = prop, fill = source)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = round(prop, digits = 3)), 
            vjust = -.05,
            position = position_dodge(0.9),
            size = 2.5)
```

```{r, 2016 registered}
to_plot_2016 <- full_data %>%
  filter(source %in% c("cces2016", "nc2016")) %>%
  group_by(source) %>%
  summarise(n = n()) %>% 
  right_join(full_data, by = "source") %>%
  group_by(source, race) %>% 
  summarise(prop = n()/median(n)) %>%
  filter(source %in% c("cces2016", "nc2016"))

ggplot(to_plot_2016, aes(x = source, y = prop, fill = race)) +
  geom_col(position = "dodge")
#zoom
ggplot(to_plot_2016, aes(source, prop, fill = race)) +
  geom_col(position = "dodge") +
 coord_cartesian(ylim = c(0,.25)) +
  geom_text(aes(label = round(prop, digits = 3)), 
            vjust = -.05,
            position = position_dodge(0.9),
            size = 3)
#extra
ggplot(to_plot_2016, aes(x = race, y = prop, fill = source)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = round(prop, digits = 3)), 
            vjust = -.05,
            position = position_dodge(0.9),
            size = 3)
```

```{r, 2012 voting viz}
full_data1 <- full_data %>%
  filter(source %in% c("cces2012", "cps2012", "nc2012vot")) %>%
  filter(voted %in% c("Voted", "Voted2012")) %>%
  mutate(source = if_else(source == "cces2012", "cces2012vot", false = source),
         source = if_else(source == "cps2012", "cps2012vot", false = source)) 
  
to_plot_2012vot <- full_data1 %>%
  group_by(source) %>%
  summarise(n = n()) %>%
  right_join(full_data1, by = "source") %>%
  group_by(source, race) %>% 
  summarise(prop = n()/median(n)) %>%
  filter(source %in% c("cces2012vot", "cps2012vot", "nc2012vot"))

ggplot(to_plot_2012vot, aes(x = source, y = prop, fill = race)) +
  geom_col(position = "dodge")
#zoom
ggplot(to_plot_2012vot, aes(source, prop, fill = race)) +
  geom_col(position = "dodge") +
 coord_cartesian(ylim = c(0,.25)) +
  geom_text(aes(label = round(prop, digits = 3)), 
            vjust = -.05,
            position = position_dodge(0.9),
            size = 2.5)
#extra
ggplot(to_plot_2012vot, aes(x = race, y = prop, fill = source)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = round(prop, digits = 3)), 
            vjust = -.05,
            position = position_dodge(0.9),
            size = 2.5)
```

```{r, 2014 voting}
full_data2 <- full_data %>%
  filter(source %in% c("cces2014", "cps2014", "nc2014vot")) %>%
  filter(voted %in% c("Voted", "Voted2014")) %>%
  mutate(source = if_else(source == "cces2014", "cces2014vot", false = source),
         source = if_else(source == "cps2014", "cps2014vot", false = source)) 
  
to_plot_2014vot <- full_data2 %>%
  group_by(source) %>%
  summarise(n = n()) %>%
  right_join(full_data2, by = "source") %>%
  group_by(source, race) %>% 
  summarise(prop = n()/median(n)) %>%
  filter(source %in% c("cces2014vot", "cps2014vot", "nc2014vot"))

ggplot(to_plot_2014vot, aes(x = source, y = prop, fill = race)) +
  geom_col(position = "dodge")
#zoom
ggplot(to_plot_2014vot, aes(source, prop, fill = race)) +
  geom_col(position = "dodge") +
 coord_cartesian(ylim = c(0,.25)) +
  geom_text(aes(label = round(prop, digits = 3)), 
            vjust = -.05,
            position = position_dodge(0.9),
            size = 2.5)
#extra
ggplot(to_plot_2014vot, aes(x = race, y = prop, fill = source)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = round(prop, digits = 3)), 
            vjust = -.05,
            position = position_dodge(0.9),
            size = 2.5)
```

```{r, 2016 voting}
full_data3 <- full_data %>%
  filter(source %in% c("cces2016", "nc2016vot")) %>%
  filter(voted %in% c("Voted", "Voted2016")) %>%
  mutate(source = if_else(source == "cces2016", "cces2016vot", false = source))
  
to_plot_2016vot <- full_data3 %>%
  group_by(source) %>%
  summarise(n = n()) %>%
  right_join(full_data3, by = "source") %>%
  group_by(source, race) %>% 
  summarise(prop = n()/median(n)) %>%
  filter(source %in% c("cces2016vot", "nc2016vot"))

ggplot(to_plot_2016vot, aes(x = source, y = prop, fill = race)) +
  geom_col(position = "dodge")
#zoom
ggplot(to_plot_2016vot, aes(source, prop, fill = race)) +
  geom_col(position = "dodge") +
 coord_cartesian(ylim = c(0,.25)) +
  geom_text(aes(label = round(prop, digits = 3)), 
            vjust = -.05,
            position = position_dodge(0.9),
            size = 3)
#extra
ggplot(to_plot_2016vot, aes(x = race, y = prop, fill = source)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = round(prop, digits = 3)), 
            vjust = -.05,
            position = position_dodge(0.9),
            size = 3)
```