---
title: "Wrangle CPS"
output: github_document
---

```{r load_packages}
library(tidyverse)
library(forcats)
```

```{r cps_wrangle}
cps <- read_csv("../data-raw/cps_12_14/cps_12_14.csv")

codebook <- list()
for (name in names(cps)){ 
  codebook[[name]] <- read_table(paste("../data-raw/cps_12_14/codebook/",
                                       name, ".txt", sep = ""), 
                                 col_names = c("code", "value"),
                                 col_types = "ic"
                                 ) %>% 
    mutate(value = ifelse(value == "NIU", NA, value))
}



recode <- function(code, code_book){
  if(is.na(code_book[[1,1]])) return(code)
  out_row <- which(code_book[,1] == code)
  if(length(out_row) != 1){
    out <- code
  } else out <- code_book[[out_row, 2]]
  out
}

for(name in names(codebook)){
  cps[[name]] <- map_chr(cps[[name]], ~ recode(.x, codebook[[name]]))
}

rm(codebook, recode, name)

cps$FAMINC <- as.factor(cps$FAMINC) %>% 
  factor(levels = levels(.)[c(16, 11, 14, 1, 3, 4, 6:10, 12, 13, 15, 2, 5)])
cps$AGE <- as.integer(cps$AGE)
```

```{r eval = F}
save(cps, file = "../../data/cps.Rda")
```

