---
title: "North Carolina voter demographics"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: yeti
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(shiny)
```

Overview
=======================================================================

### Project Overview

This is what our project is about.

Data
=======================================================================

### Data wrangling

This is what our data looked like and what we did to it

Charts
=======================================================================

Parameters {.sidebar}{.no-mobile}
-----------------------------------------------------------------------

### Parameters

Select the variables you want to see.

```{r}
sliderInput("alpha", "Transparency", 0, 1, 1)
        
selectInput("variable", "Variables", c("Race" = "race",
                                              "Age" = "age",
                                              "Gender" = "gender"),
            selected = "race", multiple = TRUE)

radioButtons("year", "Year", c(2012, 2014, 2016), selected = 2016 )
```


Parameters {.mobile}
-----------------------------------------------------------------------

Select the variables you want to see.

```{r}
sliderInput("alpha", "Transparency", 0, 1, 1)
        
selectInput("variable", "Variables", c("Race" = "race",
                                              "Age" = "age",
                                              "Gender" = "gender"),
            selected = "race", multiple = TRUE)

radioButtons("year", "Year", c(2012, 2014, 2016), selected = 2016 )
```


Main
-----------------------------------------------------------------------
### Visualizations

```{r}


temp <- sample_n(diamonds, 10000)
renderPlot({ggplot(temp, aes(carat, price)) +
  geom_point(alpha = input$alpha) +
  theme_minimal()})
```


