---
title: "tidy_cces"
author: "Edwin Alvarado"
date: "April 9, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages}
library(tidyverse)
```

```{r, import_data}
load("data/cces/CCES12_Common_VV.RData")

cces_2012 <- x

load("data/cces/CCES14_Common_Content_Validated.RData")

cces_2014 <- x

load("data/cces/CCES2016_Common_FirstRelease.RData")

cces_2016 <- x
rm(x)
```

```{r, tidy_2012}
cces_2012 <- cces_2012 %>%
  select(1:4, 6:15, faminc, CC316, CC317) %>%
  filter(inputstate == "North Carolina", votereg == "Yes")
```

```{r, tidy_2014}
cces_2014 <- cces_2014 %>%
  select(1:6, birthyr, gender, 
         educ, race, hispanic, 
         votereg, votereg_f, inputstate, 
         faminc, CC14_316, CC14_317) %>%
  filter(inputstate == "North Carolina", votereg == "Yes")
```

```{r, tidy_2016}
cces_2016 <- cces_2016 %>%
  select(1:10, votereg, votereg_f,
         regzip, inputzip,birthyr,
         gender, race, hispanic) %>%
  filter(inputstate == "North Carolina", votereg == "Yes")
```

