---
title: "Age / Gender"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(ggthemes)
library(lubridate)
```

```{r, load data}
# setwd('/Users/alisakwok/Desktop/math241/nc-elections-project')
if(!dir.exists("viz/temp")) dir.create("viz/temp")
purl("wrangle/cps.Rmd", output = "viz/temp/cps.R") %>% source()
purl("wrangle/nc_wrangle.Rmd", output = "viz/temp/nc.R") %>% source()
purl("tidy_cces/tidy_cces.Rmd", output = "viz/temp/cces.R") %>% source()
```

```{r}
set.seed(800)

cps_sample <- cps %>%
  mutate(WTFINL = as.numeric(WTFINL)) %>%
  sample_n(size = nrow(cps), replace = TRUE, weight = WTFINL)

cces_2012_sample <- cces_2012 %>%
  filter(!is.na(weight_vv_post)) %>%
  sample_n(size = nrow(cces_2012), replace = TRUE, weight = weight_vv_post)
```


```{r}
# AGE, 2012
lcolors <- c("CPS" = "#51acb4", "CCES" = "#7cb451", "VOTER" = "#b49251")

cps_2012_sample <- cps_sample %>%
  filter(YEAR == "2012", VOTEREG == "Voted") %>%
  mutate(AGE = as.numeric(AGE, na.rm = TRUE))

cps_2014_sample <- cps_sample %>%
  filter(YEAR == "2014", VOTEREG == "Voted") %>%
  mutate(AGE = as.numeric(AGE, na.rm = TRUE))

nc_2012 <- nc %>%
  filter(date_part("year", election_lbl) == 2012, age < 100) %>%
  group_by(voter_reg_num) %>%
  summarise(age = mean(age)) %>%
  as.data.frame()

nc_2014 <- nc %>%
  filter(date_part("year", election_lbl) == 2014, age < 100) %>%
  group_by(voter_reg_num) %>%
  summarise(age = mean(age)) %>%
  as.data.frame()

cces_2012_sample %>%
  mutate(birthyr = paste(birthyr, "-01-01", sep = ""),
         age = as.numeric(as.duration(ymd(birthyr) %--% mdy("01-01-2012")), "years")) %>%
  filter(votereg == "Yes") %>%
  ggplot(aes(x = age)) +
  geom_line(aes(color = "CCES"), stat = "density") +
  geom_line(data = cps_2012_sample, aes(x = AGE, color = "CPS"), stat = "density") +
  geom_line(data = nc_2012, aes(x = age, color = "VOTER"), stat = "density") +
  scale_color_manual(name = "Data", values = lcolors) +
  labs(title = "2012 NC electorate age distributions reported by the CCES, CPS, and voter file", x = "Age", y = "Density") +
  theme_solarized_2(light = FALSE)

cps_2014_sample %>%
  ggplot(aes(x = AGE)) +
  geom_line(aes(color = "CPS"), stat = "density") +
  geom_line(data = nc_2014, aes(x = age, color = "VOTER"), stat = "density") +
  scale_color_manual(name = "Data", values = lcolors) +
  theme_solarized_2(light = FALSE)
```



