---
title: "race_viz"
author: "Edwin Alvarado"
date: "April 13, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(knitr)
library(forcats)
```

```{r, load data}
if(!dir.exists("viz/temp")) dir.create("viz/temp")
purl("wrangle/cps.Rmd", output = "viz/temp/cps.R") %>% source()
purl("wrangle/nc_wrangle.Rmd", output = "viz/temp/nc.R") %>% source()
purl("tidy_cces/tidy_cces.Rmd", output = "viz/temp/cces.R") %>% source()
```

```{r, nc server}
my_db <- src_postgres("nc_elections",
                      host = "ncelections.c7d0c8vzwwoc.us-west-2.rds.amazonaws.com", 
                      port = 5432,
                      user = "nc_elections",
                      password = "nc_elections")
nc_vhis <- tbl(my_db, "nc_vhis")
nc_voter <- tbl(my_db, "nc_voter")
```

```{r, tidy cps for viz}
cps$HISPAN <- as.factor(cps$HISPAN)
cps$HISPAN <- fct_other(cps$HISPAN, keep = "Not Hispanic", other_level = "Hispanic")

#see cases that are hispanic
cps%>%
  group_by(RACE, HISPAN) %>%
  summarize(count = n())

#change race to hispanic
cps$VOTEREG <- as.factor(cps$VOTEREG)
cps <- cps %>%
  mutate(RACE = if_else(HISPAN == "Hispanic", true = "Hispanic", 
                        false = RACE, missing = RACE)) %>%
  filter(VOTEREG %in% c("Registered, did not vote", "Voted"),
         AGE >= 18)

cps$RACE <- fct_recode(cps$RACE, `Native American` =  "American Indian/Aleut/Eskimo",
                       Asian = "Asian only",
                       Black = "Black-American Indian",
                       Mixed = "Black-Asian",
                       Black = "Black/Negro",
                       Other = "Hawaiian/Pacific Islander only",
                       `Native American` = "White-American Indian",
                       Mixed = "White-Asian",
                       Mixed = "White-Black",
                       Mixed = "White-Black-American Indian")
cps_viz <- sample_n(cps, size = nrow(cps), weight = , replace = TRUE)
```

```{r, tidy cces for viz}
#this changes people who answered yes to hispanic, to hispanic in race column
cces_2012$race <- as.character(cces_2012$race)
cces_2012 <- cces_2012 %>%
  mutate(race = if_else(hispanic == "Yes", true = "Hispanic", 
                        false = race, missing = race))
set.seed(420)
cces_2012_viz <- sample_n(cces_2012, size = nrow(cces_2012), 
                          weight = weight_vv, replace = TRUE)
#2014
cces_2014$race <- as.character(cces_2014$race)
cces_2014 <- cces_2014 %>%
  mutate(race = if_else(hispanic == "Yes", true = "Hispanic", 
                        false = race, missing = race))
  
cces_2014$race <- fct_recode(cces_2014$race, Other = "Middle Eastern")

cces_2014_viz <- sample_n(cces_2014, size = nrow(cces_2014), 
                          weight = weight, replace = TRUE)
#2016
cces_2016$race <- as.character(cces_2016$race)
cces_2016 <- cces_2016 %>%
  mutate(race = if_else(hispanic == "Yes", true = "Hispanic", false = race, missing = race))
  
cces_2016$race <- fct_recode(cces_2016$race, Other = "Middle Eastern")

cces_2016_viz <- sample_n(cces_2016, size = nrow(cces_2016), 
                          weight = commonweight, replace = TRUE)
```

```{r, nc}
nc %>%
  group_by(race_code, ethnic_code) %>%
  summarize(count = n())

nc <-nc %>%
  select(race_code, ethnic_code) %>%
  filter(!is.na(race_code), 
         race_code != "U",
         !is.na(ethnic_code)) %>%
  mutate(race_code = if_else(ethnic_code == "HL", true = "Hispanic", 
                        false = race_code, missing = race_code)) %>%
  collect(n = Inf)


```

```{r, 2012 viz}
cces_2012_viz %>%
  ggplot(aes(x = race)) +
  geom_bar()

cps %>%
  filter(YEAR == 2012) %>%
  ggplot(aes(x = RACE)) +
  geom_bar()
```

```{r, 2014}
ggplot(cces_2014_viz, aes(x = race)) +
  geom_bar()

cps %>%
  filter(YEAR == 2014) %>%
  ggplot(aes(x = RACE)) +
  geom_bar()
```

```{r, 2016}
ggplot(cces_2016_viz, aes(x = race)) +
  geom_bar()
```